Deprecate logDebug and logDebugf.
blues/note-arduino pull request #125
Opened 2024-01-29 21:28 UTC by haydenroche5

These are wrappers around NoteDebug, which is really intended for internal note-c usage only. As such, we don't want users calling these functions.

2024-01-30 10:12 UTC, zfields commented
It seems like we should be using compiler directives similar to this...

```c++
#ifdef _MSC_VER
#define DEPRECATED __declspec(deprecated)
#elif defined(__GNUC__) | defined(__clang__)
#define DEPRECATED __attribute__((__deprecated__))
#else
#define DEPRECATED
#endif

//usage:
DEPRECATED void foo(int bar);
```

2024-01-30 10:16 UTC, zfields requested changes

2024-01-30 10:16 UTC, zfields commented on src/Notecard.cpp
> +    @deprecated Do not use.
> "Do not use."

should probably be replaced with:

> "NoteDebug should be treated as an internal Notecard logging function, used only by the library itself (note-arduino and note-c) and not its users."

https://www.doxygen.nl/manual/commands.html#cmddeprecated

2024-01-30 10:16 UTC, zfields commented on src/Notecard.cpp
> +    // users.
Becomes redundant if this messages is moved into the `@deprecated` section of the Doxygen comment.

2024-01-30 17:01 UTC, haydenroche5 commented
> It seems like we should be using compiler directives similar to this...
> 
> ```c++
> #ifdef _MSC_VER
> #define NOTE_C_DEPRECATED __declspec(deprecated)
> #elif defined(__GNUC__) | defined(__clang__)
> #define NOTE_C_DEPRECATED __attribute__((__deprecated__))
> #else
> #define NOTE_C_DEPRECATED
> #endif
> 
> //usage:
> NOTE_C_DEPRECATED void foo(int bar);
> ```

As I mentioned on Slack none of that works with Arduino, at least not when programming for Uno, which uses avr-gcc under the hood.

2024-02-01 15:52 UTC, zfields approved these changes

2024-02-01 19:38 UTC, merged