feat: unit-tests
blues/note-arduino pull request #30
Opened 2021-01-06 20:39 UTC by zfields

2021-01-06 20:47 UTC, bsatrom requested changes
Nice! Two comments:

1. Can you add a section to the README with instructions for running tests, including required dependencies?
2. Can we make the tests a bit more verbose and show a message after each test?

2021-01-07 00:43 UTC, robouden commented
Agreed with the suggestions.

2021-01-07 19:43 UTC, zfields commented
For the sake of posterity:

While updating this, I did investigate alternate testing frameworks. I did not see a distinct advantage to be gained for the time required to migrate the test. Unless the hand-rolled framework causes some unexpected friction, I don't see an advantage to changing at this time.

These tests were designed to be pinning tests. When we plan to refactor the implementation, we should reconsider a new testing framework at that time, and write the implementation in a manner than lends itself to be tested.

2021-01-07 23:05 UTC, bsatrom approved these changes

2021-01-07 23:05 UTC, merged